#!/bin/bash
#function to show hostname
hostname()
{
	echo "Hostname:"
	hostnamectl
	echo "Logged-in users:"
	who
	read -p "Press any key to Continue..."
}
#function to show the file system disk space usage
diskusage()
{
	echo "Disk Usage:"
	df
	read -p "Press any key to Continue"
}
#function to free and used memory
freememory()
{
	echo "Free and Used Memory:"
	free
	read -p "Press any key to Continue"	
}
#function to show the system uptime and load
uptime_load()
{
	echo "System uptime and Load:"
	uptime
	read -p "Press any key to Continue"
}
#function to show menu
show_menu()
{
       clear
       echo "++++++++++++ MENU +++++++++++++"
       echo "1. Show HOstname and Logged in Users."
       echo "2. Show Disk Space Usage"
       echo "3. Show Free Space and Used Memory."
       echo "4. Show System uptime and Load"
       echo "5. Exit."
       echo "+++++++++++++++++++++++++++++++"
}
#function to take input
take_input()
{
	local choice
	read -p "Select the option from above menu:: " choice
	case $choice in
		
		"1")
		hostname
		;;
		"2")
		diskusage
		;;
		"3")
		freememory
		;;
		"4")
		uptime_load
		;;
		"5") 
		exit 0 
		;;
				
	esac
}
while true
do
show_menu
take_input
done
